### ISSUE TITLE
[STORY] 출발국 입력

### ISSUE THREAD

**Issue by forbid403** [coronascan/coronascan#10]
- 출발국을 입력 할 수 있다.
- 초성 한 글자만 입력해도 국가명 예시가 뜬다.
- 출발국은 한 곳만 선택 가능하다.

**Comment by aimb-p** [comment]
- 기본적으로 '한국' 은 하나의 단위로만 해야 편하다. 
- 청도, 대구, 인천, 김포 이런 식으로 가면 복잡해진다
현재 기준 한국 입국 금지 국가가 36개 -> 36개 국가가 출발국이 한국일 경우 -> 배경색 검은색, 해당 국가명(도착국), 도착국 오른쪽 칸인 조치사항이 뜨도록 크롤링되게 하기.
