### ISSUE TITLE
041- 특별입국조치 시행 대상국 메뉴, 페이지 수정

### ISSUE THREAD

**Issue by aimb-p** [coronascan/coronascan#103]
https://1drv.ms/p/s!AnNpv-MNEFyBc0HbnZzw3qAnm-g?e=BWgXrl 11p 참고
0 - ‘특별입국절차’ 메뉴 생성​
1 - 제목 – 특별입국절차 대상 국가​

2 - 특별입국절차 내용 텍스트​

2-1 특별입국절차 대상국가 ​

3 – 지도 API​

4 – 020 입국제한국가 연한 분홍색으로 전 세계 덮어줘야 함​
5 – 툴팁 없앰​

​

**Comment by aimb-p** [comment]
API는 여행 경보와 마찬가지로,

**Comment by coronascan** [comment]
지도 API도 수정 부탁드립니다.
