### ISSUE TITLE
040, 041 지도 색 수정

### ISSUE THREAD

**Issue by coronascan** [coronascan/coronascan#113]
040 - DB 기준 (공통 css 기준 파일 아래 첨부 _ bg_alert)
041 - 전 세계 020의 연한 분홍색  #E7A3A2, 너무 연하면 #CB6E6D로 전 세계 적용 부탁드립니다.

**Comment by coronascan** [comment]
<img width="692" alt="color" src="https://user-images.githubusercontent.com/61606148/76918541-e1139300-6909-11ea-94ef-315f5ffe1b83.png">

**Comment by coronascan** [comment]
[최신 여행경보단계 조정]
2020-03-18 전 국가·지역 여행경보 1단계(여행유의) 발령
2020-03-16 유럽 지역 여행경보 2단계(황색경보, 여행자제) 발령
2020-03-11 이탈리아 전역 여행경보 1단계(남색경보, 여행유의) 추가 발령	
2020-03-09 이탈리아 피에몬테주 및 마르케주에 여행경보 2단계 (황색경보) 발령
2020-03-08 일본 전 지역에 여행경보 2단계(황색경보, 여행자제)로 상향 조정

**Comment by coronascan** [comment]
https://1drv.ms/p/s!AnNpv-MNEFyBc0HbnZzw3qAnm-g?e=8b7l6P 검수 PPT 5P

**Comment by greyay** [comment]
최신 여행경보단계 update완료

**Comment by aimb-p** [comment]
기존

내·외국인 특별입국 절차
내·외국인 건강 상태 질문서, 특별 검역 신고서 제출 의무
1대 1 발열 검사, 국내 체류 주소, 연락처 제출
입국 후 자가 진단 앱 설치 후 매일 건강 상태 제출 의무
유증상시 1399 연계 및 선별 진료소 안내, 무응답시 유선 확인

대상 국가
03.19 0시부터 국내에 입국하는 모든 내·외국인 대상 특별입국 절차 적용
03.16 0시부터 유럽발 국내 입국자에 특별입국 절차 적용
03.12 이탈리아, 프랑스, 독일, 스페인, 영국, 네덜란드발 국내 입국자에 특별입국 절차 적용
03.12 이탈리아, 이란발 국내 입국자에 특별입국 절차 적용
03.09 일본발 국내 입국자에 특별입국 절차 적용
02.04 중국발 국내 입국자에 특별입국 절차 적용

-> 

유럽발 입국자 전원 코로나19 진단검사 시행
유증상자 - 검역소 격리시설, 무증상자 - 지정 임시생활시설에서 검사
내국인, 장기체류 외국인 14일 격리 조치(생활지원금, 유급휴가비 정부지원) 
단기 체류 외국인 14일간 능동감시(전화로 본인 건강 상태 설명) 

내·외국인 특별입국 절차
내·외국인 건강 상태 질문서, 특별 검역 신고서 제출 의무
1대 1 발열 검사, 국내 체류 주소, 연락처 제출
입국 후 자가 진단 앱 설치 후 매일 건강 상태 제출 의무
유증상시 1399 연계 및 선별 진료소 안내, 무응답시 유선 확인

대상 국가
03.22 유럽발 입국 내·외국인 대상 코로나 19 진단검사 시행
03.19  국내에 입국하는 모든 내·외국인 대상 특별입국 절차 적용
03.12 이탈리아, 프랑스, 독일, 스페인, 영국, 네덜란드발 국내 입국자에 특별입국 절차 적용
03.12 이탈리아, 이란발 국내 입국자에 특별입국 절차 적용
03.09 일본발 국내 입국자에 특별입국 절차 적용
02.04 중국발 국내 입국자에 특별입국 절차 적용
