### ISSUE TITLE
[STORY] 입국할 국가 입력

### ISSUE THREAD

**Issue by forbid403** [coronascan/coronascan#12]
- 조회를 원하는 국가를 선택할 수 있다.
- 모든 나라를 조회할 수 있다. (default)

**Comment by aimb-p** [comment]
현재 한국 입국 금지 국 36개 기준 -> 이 나라들이 해당된다면 입국 금지.
48개 입국 제한 조치국 -> 이 나라들에 해당된다면 빨간 배경화면 뜨고, 조치사항 셀이 자동으로 입력되도록.
