### ISSUE TITLE
[STORY] CS-020 지도 벡터에 국가별 제한조치 넣기

### ISSUE THREAD

**Issue by aimb-p** [coronascan/coronascan#21]
지도로 보는 입국제한국가

**Comment by aimb-p** [comment]
https://www.notion.so/85e13620dbc84b88a5b4f5f6761994bd
dhl

입국금지
-한국 전역에 대한 입국금지 조치 : 33개 국가, 지역
-대구, 청도 등 일정 지역에 대한 입국금지 조치 : 5개 국가, 지역

제한조치
-격리 조치 : 22개 국가, 지역 (중국 / 기타 국가)
-검역 강화 및 권고 사항 : 34개 국가, 지역
이렇게 새롭게 분류되었습니다.

**Comment by forbid403** [comment]
- 지도 API에서 지원하지 않는 국가들을 위도, 경도별로 표시할 수 있는지 확인해야 함

**Comment by forbid403** [comment]
- API 지원이 되지 않는 국가들은 Listview로 따로 빼도록 결정
