### ISSUE TITLE
[TASK] 외교부 공지사항 크롤링 -> 데이터 만들기

### ISSUE THREAD

**Issue by aimb-p** [coronascan/coronascan#23]
http://www.0404.go.kr/dev/notice_view.mofa?id=ATC0000000007689&pagenum=1&st=title&stext=
3.3 오전 9시 기준 PDF

입국 금지/제한조치 대상국가(3.3 오전 9시 외교부 문서 기준)​
-> 한국, 중국, 대만, 홍콩, 마카오, 싱가포르, 태국, 쿠웨이트, 이탈리아, 일본, 이란, 나이지리아, 이집트, 알제리​

로직 구현​

입국할 국가​ (CS-031 기준)
-입국 금지조치를 시행하는 국가 -> 36개 지역​
-입국 제한조치를 시행하는 국가 -> 중국 13개 지역, 그 외 50개 국가 리스트업, 벡터값 설정, 국가별로 제한 조치 크롤링하기

1. 입국 금지 국가에 해당된다 -> 배경 검은색, 입국금지 제목, 국가명, 기준일자 시간, 국가명 옆의 칸인 입국 제한 조치가 그대로 박스칸에 출력​

2. 입국 제한 국가에 해당된다 -> 배경 빨간색, 국가명, 입국제한조치 제목 출력, 국가명, 기준일자시간, 국가명 옆의 칸인 입국 제한 조치가 그대로 박스칸에 출력​

3. 해당 없음 -> 배경 초록색 ​
​

**Comment by forbid403** [comment]
https://www.npmjs.com/package/pdf2svgpdf->svg 모듈
모듈 이용해 pdf->svg 변환

**Comment by aimb-p** [comment]
https://www.notion.so/85e13620dbc84b88a5b4f5f6761994bd
dhl

입국금지
-한국 전역에 대한 입국금지 조치 : 33개 국가, 지역
-대구, 청도 등 일정 지역에 대한 입국금지 조치 : 5개 국가, 지역

제한조치
-격리 조치 : 22개 국가, 지역 (중국 / 기타 국가)
-검역 강화 및 권고 사항 : 34개 국가, 지역
이렇게 새롭게 분류되었습니다.

**Comment by forbid403** [comment]
- DB Collection 설계 완료.
- 슬랙 참고 해 주세요!
