### ISSUE TITLE
[EPIC] CS-040 한국 외교부 권고사항

### ISSUE THREAD

**Issue by forbid403** [coronascan/coronascan#6]
한국 외교부 권고사항 조회

**Comment by aimb-p** [comment]
https://www.notion.so/85e13620dbc84b88a5b4f5f6761994bd
dhl

입국금지
-한국 전역에 대한 입국금지 조치 : 33개 국가, 지역
-대구, 청도 등 일정 지역에 대한 입국금지 조치 : 5개 국가, 지역

제한조치
-격리 조치 : 22개 국가, 지역 (중국 / 기타 국가)
-검역 강화 및 권고 사항 : 34개 국가, 지역
이렇게 새롭게 분류되었습니다.
