### ISSUE TITLE
[STORY] CS-020 제한 조치 시행국 지도로 보기

### ISSUE THREAD

**Issue by forbid403** [coronascan/coronascan#8]
- 크롤링을 통해 외교부에서 데이터 긁어오기
- 지도로 입국금지된 국가 확인 가능

**Comment by aimb-p** [comment]
https://www.notion.so/85e13620dbc84b88a5b4f5f6761994bd
dhl

입국금지
-한국 전역에 대한 입국금지 조치 : 33개 국가, 지역
-대구, 청도 등 일정 지역에 대한 입국금지 조치 : 5개 국가, 지역

제한조치
-격리 조치 : 22개 국가, 지역 (중국 / 기타 국가)
-검역 강화 및 권고 사항 : 34개 국가, 지역
이렇게 새롭게 분류되었습니다.
